### ISSUE TITLE
EV Charger Archivist Sample - No Highlighting/Bolding

### ISSUE THREAD

**Issue by mmwilder26** [jitsuin-inc/archivist-samples#32]
**Describe the bug**
EV Charger archivist sample does not highlight/bold update, vulnerability and maintenance events.

Had to make manual changes to the below py files:
ev_charger_device.py
props, attrs = make_event_json(
                #"Maintenance",
                #"MaintenanceRequired",
                "RecordEvidence",
                "Record",
                dtstring,
                f"{self._archivist_asset_identity[7:]}@evc.m2m.synsation.io",
                #"Service RQ",
                "Maintenance Request",
                maint_msg,
                corval,
            )

props, attrs = make_event_json(
                #"Firmware",
                #"Update",
                "RecordEvidence",
                "Record",
                dtstring,
                "otaService@evcservicing.com",
                #"FW Update",
                "Vulnerability Addressed",
                patch_msg,
                cve_corval,
            )

maintenance_worker.py
props, attrs = make_event_json(
        #"Maintenance",
        #"Maintenance",
        "RecordEvidence",
        "Record",
        dtstring,
        "Phil@evcservicing.com",
        #"Service RP",
        "Maintenance Performed",
        maint_msg,
        job_id,
    )

recall_worker.py
props, attrs = make_event_json(
            #"Firmware",
            #"Vulnerability",
            "RecordEvidence",
            "Record",
            dtstring,
            "VulnBot@synsation-industries.com",
            #"FW Vulnerability",
            "Vulnerability Report",
            recall_msg,
            cve_corval,
        )
**To Reproduce**
1. Execute ev charger archivist sample
2. None of the maintenance, update or vulnerability events are highlighted/bolded.

**Expected behavior**
For the maintenance, update and vulnerability events to be highlited/bolded.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: Version 96.0.4664.93 (Official Build) (x86_64)

**Comment by JAG-UK** [comment]
In the event.attributes.arc_display_type you shouldn’t use the BEHAVIOUR:OPERATION pairs - those are from the legacy API. 

Anyone wishing to make a PR for this issue please use the following set of event arc_display_type:
 - “Maintenance Request”
 - “Maintenance Performed”
 - “Vulnerability Report”
 - “Vulnerability Adressed”
