### ISSUE TITLE
Synsation charger sample erroring on expected arguements

### ISSUE THREAD

**Issue by mmwilder26** [jitsuin-inc/archivist-samples#36]
When executing TEST_SELECTOR=sysnation_charger task samples the below renders.  Used date as the namespace.

mwilder@Madias-MBP.attlocal.net:~/mmwilder26/archivist-samples$TEST_SELECTOR=synsation_charger task samples
task: [about] ./scripts/api.sh ./scripts/version.sh
task: [samples] ./scripts/api.sh ./scripts/samples.sh
NAMESPACE is 1644600094
usage: __main__.py [-h] [-v] [-u URL] [-p {KHIPU,SIMPLE_HASH}] -t
                   AUTH_TOKEN_FILE [--namespace NAMESPACE] [-w WAIT]
                   [-a AIRPORT] [-s START_DATE] [-S STOP_DATE]
                   [-f FAST_FORWARD]
__main__.py: error: argument -s/--start-date: invalid <lambda> value: 'top-date'

**To Reproduce**
1. Ran TEST_SELECTOR=synsation_initialise task samples
2. After the above finished ran TEST_SELECTOR=synsation_charger task samples
3. And received the above error.

**Expected behavior**
The sample to run and create assets for ev charger assets that have been created

**Desktop (please complete the following information):**
 - Mac OS
 - Chrome 
 - Version 98.0.4758.80 (Official Build) (x86_64)

**Comment by JAG-UK** [comment]
Reproduced this. Will fix alongside update to this sample.
